version: '3.8'

services:
  boot-node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOOT_NODE=true
      - DISCOVERY_TYPE=gossip
      - PORT=3000
      - BOOT_NODE_URI=192.168.100.100:3000
    volumes:
      - ./tmp:/app/tmp
    ports:
      - "3000:3000"
    networks:
      custom-network:
        ipv4_address: 192.168.100.100

  raft-node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOOT_NODE=false
      - DISCOVERY_TYPE=gossip
      - PORT=3000
      - BOOT_NODE_URI=192.168.100.100:3000
    volumes:
      - ./tmp:/app/tmp
    depends_on:
      - boot-node
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24