version: '3.8'

services:
  boot-node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2001:2001"
    environment:
      - BOOT_NODE_URI=boot-node-service
      - BOOT_NODE_PORT=8080
    command: ["--bootNode"]

  raft:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BOOT_NODE_URI=boot-node-service
      - BOOT_NODE_PORT=8080
    depends_on:
      - boot-node